In [7]:
a=5
b=7
c=a+b
c

12

In [8]:
print(type(c))

<class 'int'>


In [11]:
input()

12


'12'

In [12]:
type(a)

int

In [14]:
a=int(input())

56


In [15]:
type(a)

int

In [17]:
if a < 10: 
        print(a)
else: 
    print("hello")

hello


In [46]:
a=int(input())
b=int(input())
c=int(input())
if a>b and a>c:
    print (a)
    if b>c:
        print (b)
else:
    print (c)

56
12
78
78


In [26]:
if a>b:
    if a>c:
        print(a)
         else
        print(b)
    

IndentationError: unexpected indent (<ipython-input-26-35c2d6942c91>, line 4)

In [28]:
string="hello world"


In [31]:
string[0:11:2]

'hlowrd'

In [33]:
string.capitalize()

'Hello world'

In [35]:
string.count("o")

2

In [39]:
string.find("w")

6

'dlrow olleh'

In [77]:
string="Welcome to AI Workshop"
string.split()

['Welcome', 'to', 'AI', 'Workshop']

In [79]:
mylist.reverse()

In [80]:
mylist

[0.1, 'y', 3, 0]

In [81]:
j=string.split()

In [82]:
j

['Welcome', 'to', 'AI', 'Workshop']

In [83]:
j.reverse()

In [89]:
j

NameError: name 'j' is not defined

In [85]:
" ".join(["Workshop","AI","to","Welcome"])

'Workshop AI to Welcome'

In [ ]:
for i in range (5,20,5):
    print(i)

In [96]:
for i in range(3):
    for j in range (len(mylist)):
        print(mylist[i])

Workshop
Workshop
Workshop
Workshop
AI
AI
AI
AI
to
to
to
to


In [97]:
mylist = [1,2,3,5]
for i in range(3):
    for j in range (3):
        print(i,j)

0 0
0 1
0 2
1 0
1 1
1 2
2 0
2 1
2 2


In [98]:
import numpy as np

In [103]:
mylist = [[1,2,3],[4,5,6],[7,8,9]]
arr=np.array(mylist)

In [104]:
mylist

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [105]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [106]:
arr[1][2]

6

In [112]:
np.linspace(0,10,1)

array([0.])

In [113]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [119]:
np.([2,5])

AttributeError: module 'numpy' has no attribute 'fives'

In [120]:
for i in range (0,10):
    arr[[i]]np==5

IndexError: index 3 is out of bounds for axis 0 with size 3

In [126]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [130]:
np.linspace(10,50,41)

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19., 20., 21., 22.,
       23., 24., 25., 26., 27., 28., 29., 30., 31., 32., 33., 34., 35.,
       36., 37., 38., 39., 40., 41., 42., 43., 44., 45., 46., 47., 48.,
       49., 50.])

In [131]:
np.random.randint(0,8,(3,3))

array([[6, 4, 2],
       [4, 7, 0],
       [6, 2, 3]])

In [139]:
arr.linspace(0.01,1,100)

AttributeError: 'list' object has no attribute 'linspace'

In [145]:
np.linspace(0.01,1.00,100).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [149]:
import sklearn as sk